CREATE TABLE tasks (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255)
);

ALTER TABLE tasks ADD COLUMN user_id INTEGER REFERENCES users(id)
CREATE table users(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURREMT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURREMT_TIMESTAMP
)

ALTER TABLE users ADD COLUMN avatar VARCHAR(255)